### ISSUE TITLE
ResolutionSetting has no effect on outputs

### ISSUE THREAD

**Issue by tmhungcode** [aspose-imaging/Aspose.Imaging-for-Java#13]
I want to convert an image (png, jpg, jpeg, tiff) to TIFF with a new resolution. I tried a number of examples in this repo and the resolution of outputs remained unchanged.
SavingRasterImageToTIFFWithCompression.java
```
     TiffOptions options = new TiffOptions(TiffExpectedFormat.Default);
        options.setBitsPerSample(new int[] { 8, 8, 8 });
        options.setPhotometric(TiffPhotometrics.Rgb);
      // already tried        options.setResolutionSettings(new ResolutionSetting(100, 100));
        options.setXresolution(new TiffRational(200));
        options.setYresolution(new TiffRational(200));
        options.setResolutionUnit(TiffResolutionUnits.Inch);

```

---------

I also looked into other image outputs like JPEG. They have the same problem
ConvertTIFFToJPEG.java
```

                JpegOptions saveOptions = new JpegOptions();
                // The provided tiff's resolution is (Horizontal=200,Vertical=100), I put some numbers and outputs didn't change
                saveOptions.setResolutionSettings(new ResolutionSetting(tiffFrame.getHorizontalResolution(), tiffFrame.getVerticalResolution()));
```

---------

SettingResolution.java. This one has a bug. It always produced that image
![image](https://user-images.githubusercontent.com/2813016/82809247-dea75980-9eb5-11ea-969d-3013dc956016.png)
```
            // Create an instance of PngOptions, Set the horizontal & vertical resolutions and Save the result on disc
            PngOptions options = new PngOptions();
            options.setResolutionSettings(new ResolutionSetting(72, 96));
            png.save(Utils.getOutDir() + "SettingResolution_output.png", options);
```

**Comment by ESidenko** [comment]
Hello @tmhung88!
This is not a bug! 
Please, take in account that ResolutionSetting intended for set **a Spatial resolution** (dpi) but it does not change **a Pixel resolution**. If you wish change **a Pixel resolution**, please use Image.resize method.
