### ISSUE TITLE
DicomOptions() getting stucked

### ISSUE THREAD

**Issue by dudu3000** [aspose-imaging/Aspose.Imaging-for-Java#14]
I'm trying to add this library to compress some Dicom images.
Creating an object using `DicomOptions options = new DicomOptions();` will stuck the process and no error comes out, no logs and it doesn't move on to next lines.
Java version: `java version "1.8.0_202"`
Library version: `aspose-imaging-21.11-jdk16.jar`
(I used this library version since `aspose-imaging-18.2-jdk16.jar` doesn't contain DicomOptions.)
Anyone had this issue?

Edited: This seems to be the error that comes up using `try-catch`:<br>
`java.lang.NoSuchMethodError: com.aspose.imaging.imageoptions.DicomOptions.setFullFrame(Z)V`

**Comment by ESidenko** [comment]
@dudu3000 
Actually, DicomOptions does not have the setFullFrame method. Maybe you need to call the setCompression method?

**Comment by dudu3000** [comment]
Hi, thanks for replying.

First of all, I wasn't calling that method, I was trying to create an object of the class.
Second, I've just discovered that my build don't copy the library to the right directiry, after fixing this problem on my side, there are no errors anymore.

I'll delete this issue. Thanks again for the support
