### ISSUE TITLE
is this support   AntiAliasGridFit in winform?

### ISSUE THREAD

**Issue by ljzj2** [aspose-imaging/Aspose.Imaging-for-Java#17]
I wonder if this repo support in winform?
does it draw text same ?

**Comment by sam199008** [comment]
@ljzj2 , thank you for your question. We will investigate it and reply you.

**Comment by Sitkovic** [comment]
Hello, @ljzj2 ! 
This is Aspose.Imaging-for-Java repository, while WinForm requires .Net version.
If you mean `TextRenderingHint.AntiAliasGridFit`, then both .Net and Java draw the text using this hint the same or close to the effect you can see in GDI+.
Hope this helps!
